### PR TITLE
I257 Fixed Institution Page Bugs

### LINKED ISSUE #257: Fix institution bug
## Basic Information
These Bugs were found by Keeley in production.

Admin Institution:
"small bug, on the website if I click on institutions, go back to the main page and then click on institutions again - each time the list of schools duplicates. it resets back to normal amount if webpage is closed and opened"
`While tackling this issue, check if any other pages on team coordinator/admin have this issue`

Admin Edit institution: 
"when editing institutions (already entered without codes) app will not allow user to make changes and then save without now adding a code"
- Potential fix: FormField has required but you can pass in a new a required boolean prop

### PR DESCRIPTION
**Pull request by rezbyte**
## Change Summary
- Fixed the institutions duplicating when leaving the institutions page & entering again
- Fixed the institutions edit modal not loading the institution's `code`
- Remove `then()` clauses in `await` statements.

### Change Form
- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
I'm not sure whether the `code` field in the institutions are meant to be optional or not.

# Related issue

- Resolve #257

### CODE REVIEW

File: stores/institutions.js [hunk 1]
```diff
@@ -25,6 +25,7 @@ export const useInstitutionStore = defineStore("institution", {
   getters: {},
   actions: {
     async getInstitutions() {
+      this.institutions = [];
```
Comment (ChantelleKerr) [inline stores/institutions.js:28]: For some reason having this breaks the drop down menu on team coordinator when they first setup their institution. The list doesnt display when I comment it out it works fine, I dont understand why ahah. Tested using (tc@tc.com account)

File: stores/institutions.js [hunk 2]
```diff
@@ -125,6 +126,7 @@ export const useInstitutionStore = defineStore("institution", {
           name: institution.name,
           email: institution.email,
           number: institution.number,
+          code: institution.code,
```
Comment (ChantelleKerr) [inline stores/institutions.js:129]: This causes problems for adding a new institution profile from the team coordinator, it doesnt add it to the database. But good spot it's definitely needed for the admin view.

**Review by ChantelleKerr — CHANGES_REQUESTED** [review]
Hey jamie nice spot, but you didnt handle everything from the issue. 

They want to be able to make updates to an institution that doesn't have a code so the code should not be a required field. It is a problem with the formfield.

File: stores/institutions.js (hunk 1 above)
Comment (rezbyte) [reply stores/institutions.js:28]: This should be fixed now. :slightly_smiling_face:

File: stores/institutions.js (hunk 2 above)
Comment (rezbyte) [reply stores/institutions.js:129]: As far as I can see, this function (`createInstitution()`) isn't used in the team coordinator institutions page.
If its going to be added in the future, you could pass in the value with an undefined `code` field.
This would add the institution to the database without the code.

Comment (ChantelleKerr) [reply stores/institutions.js:129]: coordinator/institutions.vue calls checkInsititution which calls createInstitution

Comment (rezbyte) [reply stores/institutions.js:125]: I've added a line to make sure `code` is undefined before calling `checkInstitiution`.

**Review by ChantelleKerr — CHANGES_REQUESTED** [review]
Something has broken the team coordinator school name selection dropdown, if a school thats already in the dropdown has been clicked it shouldnt be creating a new institution. It should only update the user profile with that institution id

Screen Shot 2023-02-12 at 12 11 33 pm

This bug that was in the original issue has still not been fixed. If code doesn't exist it should not be a required field when trying to update other fields.

Screen Shot 2023-02-12 at 12 21 34 pm

Please try stick to whats been asked in the issue.

**Review by ChantelleKerr — APPROVED** [review]
Looks good! Thanks Jamie and goodluck in Germany! :D
