### PR TITLE
I196 incorrect error codes in team rego

### LINKED ISSUE #196: Incorrect error codes in team rego
## Basic Information
the sum of Tuesday and Wednesday allocations must equal the total teams for that level before the form can submitted

## Other Information
bug fix

### PR DESCRIPTION
**Pull request by NicholasJDavies**
## Change Summary
Changes to team rego:
> fixed hardcoding -- was causing a bug.
> now checks if tournament is chosen
> now checks if team is selected but 0 total chosen
> now ensures somebody cant enroll more than 50 teams of a specific division at once. 
> renamed function "registerTeam" -> "registerTeams"
> made error messages more descriptive

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

# Related issue

- Resolve #196

### CODE REVIEW

File: stores/institutions.js [hunk 1]
```diff
@@ -169,62 +165,46 @@ export const useInstitutionStore = defineStore("institution", {
...
+        const numTeam = parseInt(team.teams[i].numberOfTeams);
+        const tueAllocation = parseInt(team.teams[i].allocatedTue);
+        const wedAllocation = parseInt(team.teams[i].allocatedWed);
+        if (numTeam <= 0) {
           this.errorMessage =
-            "Please allocate a positive number of teams for NOVICE";
-        } else if (tueAllocation > numTeam || wedAllocation > numTeam) {
-          this.errorMessage = "Too many teams allocated to a single day.";
-        } else if (numTeam > tueAllocation + wedAllocation) {
+            team.teams[i].teamLevel + " selected but no total teams selected.";
```
Comment (ChantelleKerr) [inline stores/institutions.js:182]: This displays when a level is not selected

**Review by ChantelleKerr — CHANGES_REQUESTED** [review]
Just putting the change in writing so no one else approves it :)

**Review by ChantelleKerr — APPROVED** [review]
great job! :)
